name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 20.5.1
  PNPM_VERSION: 8.7.5

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: GIT – Checkout
        uses: actions/checkout@v4
      - name: PNPM – Install
        uses: lskjs/action-pnpm@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          command: pnpm test
